### ISSUE TITLE
Not able to download anything

### ISSUE THREAD

**Issue by R8NDOLPH** [Wulfre/e621dl#12]
I ran it on python 3 and it gave me this when I ran it : 

`Traceback (most recent call last):
  File "e621dl.py", line 107, in <module>
    results = remote.get_posts(search_string, min_score, earliest_date, last_id, session)
  File "C:\Users\(unimportnant garbo)\e621dl-4.4.0\e621dl-4.4.0\lib\remote.py", line 16, in get_posts
    response.raise_for_status()
  File "C:\Users\andol\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://e621.net/post/index.json`

**Comment by Wulfre** [comment]
Error 500 means something happened on e621's side. Try it again later and let me know if the issue still occurs.

**Comment by Wulfre** [comment]
You likely got that error because there were no new posts for that search in the past 1 day. I just ran with your config myself and found 1 result that was uploaded 6 hours before this reply (11:41pm EST).  

You might want to increase your days limit to allow some room for error. I will probably catch that error in a future version and provide an explanation in-terminal, since it has happened before.

**Comment by Wulfre** [comment]
Fixed the 500 server error. I had been testing on a 32-bit virtual machine and that is where the issue stems from. 64-bit systems were the ones vulnerable to the error.
