### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by lylatveteran** [Wulfre/e621dl#26]
Is there a way to change the download folder location? I want it on a different drive but don't see a way to make it happen.

**Comment by Wulfre** [comment]
There is no way to change the download location as of now. Since all the configuration is manual I've left it as simple as possible to avoid anyone making an error. It may be possible to add an advanced configuration section, but for now the simplest way to change the location is just to move the entire script to where you want the images saved.

**Comment by lylatveteran** [comment]
That's actually the answer to the problem. Thanks! And also thanks for the quick response.
________________________________
