### ISSUE TITLE
E621DL not running on Ubuntu 18.04

### ISSUE THREAD

**Issue by DAMaas** [Wulfre/e621dl#27]
Edit: I am incompetent, forgot to add text :')

I get this error when I ran it the second time. I made the config file and ran the program when this happened

root@DegenerateDownloads:~/e621dl-4.4.1# python3 e621dl.py
e621dl      INFO     Running e621dl version 4.4.1.

e621dl      INFO     Checking for partial downloads.

e621dl      INFO     Parsing config.

Traceback (most recent call last):
  File "e621dl.py", line 125, in <module>
    print('\u250c' + '\u2500' * row_len + '\u2510')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-71: ordinal not in range(128)

**Comment by Wulfre** [comment]
I should really release the master branch soon.

Python is having trouble reading the encoding of the file properly since I wrote the file on Windows. For now you can either download the master branch, which should be stable enough for use, I'm going to add a few tweaks and release it since you reminded me, or you can add these magic comments to the top of `e621dl.py`.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
```

**Comment by DAMaas** [comment]
Thanks for the reply, I'mma setup Ubuntu again and try again. I'll let you know if it fails or works again :)
