### ISSUE TITLE
Checkmark issue

### ISSUE THREAD

**Issue by RedLXIX** [Wulfre/e621dl#39]
Glad it's back and working with the new changes to e621! Thanks for your hard work!

I updated my copy of it and I was getting
> Traceback (most recent call last):
>   File "e621dl.py", line 115, in <module>
>     print(f"[\u2713] Post {post['id']} is being downloaded.")
>   File "~~~~~~~~~~\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 1: character maps to <undefined>

when I ran it.

I looked and it appeared my system doesn't like the checkmark in `print(f"[✓] Post {post['id']} is being downloaded.")`. I don't know if that's a windows thing, a windows 7 thing, a python thing, or a python 3.7 thing. Obviously since it's your code you don't have problems, but would you happen to be familiar with the issue? I'm not so up on the python, so I'm not sure what to do to resolve it.

Thanks again for your work on this!

**Comment by Wulfre** [comment]
I'm running Windows 10 currently, but I do all my Python stuff through Arch Linux on WSL, so I don't have a reference for what happens directly on Windows. I'm also running Python 3.8 but that shouldn't change much since Python 3 uses Unicode by default.

The simplest fix for now would be to just replace all the check marks and crosses with some other character and see if that works. I'll see if I can find a more permanent fix.
