### ISSUE TITLE
Damaged file checker searches entire download directory

### ISSUE THREAD

**Issue by tanedaa** [Wulfre/e621dl#5]
So I noticed this a couple days back when I was making a sort of GUI for the app for personal use. Basically, I have my entire library (currently 70GB+) in the same folder as the new downloads. The script always freezes when it's done downloading a new tag group, because it checks for damaged files in the entire downloads folder. Certainly this isn't a really big issue (could always move older downloads into a different folder), but could potentially use the improvement of only checking the newly downloaded tag groups (unless told otherwise?) in the downloads folder. Just an observation!

**Comment by Wulfre** [comment]
Way to get back to this issue after 2 months, I know. I have removed the damage check in the latest version, because damaged files were mostly a side effect of my bad file download code and also my constant force-closing of the program during testing. If anyone does come across a lot of damage files though, I will definitely go back and sort out this issue.
