### ISSUE TITLE
I can't run the new version e621dl-3.2.0

### ISSUE THREAD

**Issue by xiveslestian** [Wulfre/e621dl#6]
I can't run the new version e621dl-3.2.0

I tried installing python-2.7.13, e621dl-3.2.0 did not work.
I tried installing python-3.6.1, e621dl-3.2.0 did not work.
I tried installing python-3.6.1-amd64, e621dl-3.2.0 did not work.

e621dl-3.1.1 still works with python-2.7.13

So how do i get e621dl-3.2.0 to work?

Thanks!

**Comment by Wulfre** [comment]
You should be using python 3, amd64 if you are using a 64 bit operating system. When you run the e621dl, it will likely tell you to run the command  `pip install -r requirements.txt`. That is a very important step in order to run the new version, because it uses a new library to download posts. 

Let me know if that was the problem, or if I need to fix something.

**Comment by xiveslestian** [comment]
Is it possible to make a windows exe that can be run without python installed?

**Comment by xiveslestian** [comment]
I found py2exe but can't get it to create an working executable, i am not good at this ;(
Could you spare some of your time and make a working windows exe for the new version?

**Comment by Wulfre** [comment]
I'll see what I can get done tomorrow. I haven't looked at the source code in a while, so I'll clean it up over the day release an exe once I figure that out also.

**Comment by xiveslestian** [comment]
Any progress with windows exe?

**Comment by Wulfre** [comment]
I have the exe file made, but you still need python installed to make it work. All the exe file really does is make the code run a bit faster because it doesn't need to be interpreted anymore. I've been looking at what I can do for a little while each day during my free time, but with what I know so far, there isn't a way to not have python installed.
